### PR TITLE
WIP: Generate autosummary for API

### PR DESCRIPTION
**Pull request by rob-luke**
Following discussion in https://github.com/mne-tools/mne-nirs/pull/114 I thought I could suggest the same change to this template too.

### CODE REVIEW

**Comment by agramfort** [comment]
CI complain https://github.com/mne-tools/mne-project-template/pull/4/checks?check_run_id=771303396

thanks for taking the initiative @rob-luke

**Comment by agramfort** [comment]
CI still complain. Does it work on your machine?

try to avoid opening PRs from your master branch. It's harder for me then to test your branch and push to it to help

**Comment by rob-luke** [comment]
> CI still complain. Does it work on your machine?

It works if I run ‘make html’ three times. It took me a while to realise this, that’s why I pushed too early.


> try to avoid opening PRs from your master branch. It's harder for me then to test your branch and push to it to help

Yeah sorry that was a mistake. Apologies.

I think I’ll close this PR and start fresh when I’ve got a chance to look at this again.

**Comment by agramfort** [comment]
ok

>

**Comment by larsoner** [comment]
This looks like a bug with autosummary and/or the GitHub action, possibly someone is not using directories relative to the doc root when they should be (or the GitHub action should run from within the `doc/` folder so that it does not matter)

**Pull request closed without merging**
